//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Astar{
	
	/// <summary>
	/// Arc connects two nodes
	/// </summary>
	public class Arc{
		
		public Node node0;
		public Node node1;
		
		public Arc(Node node0, Node node1){
			this.node0 = node0;
			this.node1 = node1;
		}
		
		public bool Connects(Node node) {
			bool ret = node == node0;
			ret |= node == node1;
			return ret;
		}
		
		/// <summary>
		/// Return the other node connected to this arc (null if not connected by this arc).
		/// </summary>
		/// <param name="node">Node.</param>
		public Node Other(Node node) {
			return node == node0 ? node1 : node == node1 ? node0 : null;
		}
	}
}

