//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Astar
{
	abstract public class Graph
	{
		abstract public int nodeCount {get;}
		abstract public float spacing {get;set;}
		abstract public Node FindNearestNode(Vector3 location);
		abstract public Node FindNearestUnobstructedNode(Vector3 location);
		abstract public void DrawNodes();
		abstract public void DrawGizmos();
		abstract public void RevealObstacles();
	}
}

